Map<String, String> france = {
  // drawer
  "Update Residence": "Modifiez la  Résidence",
  "bookingReq": "Demande de réservation",
  "myResindence": "Mes residences",
  "income": "Revenus",
  "setting": "Paramètre",
  "support": "Supports",
  "aboutUs": "À propos de nous",
  "logOut": "Déconnexion",
  "Booking Details": "Les détails de réservation",
  "You sure want to Residence": "Vous voulez certainement résider",
  "Yes": "Oui",
  "No": "Non",
  "Edit": "Modifiez",
  "Delete": "Supprimer",
  "History": " Historique",
  "You sure want to delete message?": "Voulez-vous vraiment supprimer le message ?",
  "Edit Profile": "Modifiez le profil",
  "Profile": "Profil",
  "Save": "Sauvegardez",
"Share the app" : "Partagez l'application",

  "residenceDetails": "Détails de la résidence",

  "No Data Found": "J'y travaille",
  //onboard

  "subWelcome": "Votre solution de réservation.",
  'Get Started': "Commencez",
  "Forget Password": "Mot de passe oublié",
  "Booking List": "Liste de réservation",

  //auth

  "welcome": "Bienvenue sur Resid+ Pro",
  "email": "Email",
  "password": "Mot de passe",
  "signIn": "Se connecter",
  "doYouHaveAc": "Vous n'avez pas de compte ?",
  "Forgot Password": "Mot de passe oublié",
  "name": "Nom",
  "dob": "Date de naissance",
  "phoneNum": "Numéro de téléphone",
  "confirmPassword": "Confirmez le mot de passe",
  "signUp": "S'inscrire",

  "Enter your email": 'Entrez votre email',
  "Enter your Password": 'Entrez votre  mot de passe',
  "Please enter a valid email.": "Entrez un email valide",
  "Please enter the OTP code.": "Entrez votre code OTP",
  "Please enter your email address to reset your password.":
      "Entrez votre adresse email pour renitialiser votre mot de pass",
  "Did not get the OTP?": "Pas recu le OTP",
  "Resend OTP": "Renvoyer l'OTP",
  "Enter your name": "Entrez votre Nom",

  "*Must enter your date of birth": "*Doit entrer votre date de naissance",
  "*Must enter your valid number": "*Vous devez entrer votre numéro valide",

  "Enter Your Address Here": "Entrez votre adresse ici",
  "Enter your number": "Entrez votre numéro",

  "or": "Ou",
  // home
  "newResidence": "Ajoutez une résidence",
  "searchResidence": "Recherchez une résidence",
  "All": "Tous",
  "New": "Nouveau",
  "Popular": "Populaire",

  "hotel": "chambre",
  "residence": "résidence",
  "personal-house": "maison personnelle",

  "seeAll": "Voir tous",

  "booking ": "Reservation",
  "host": "Gérant",
  "user": "Utilisateur",
  "userInformation": "Infos Utilisateurs",
  "hostInformation": "Infos Géran",
  "userList ": "Liste d’utilisateurs",
  "search": " Recherche",
  "contact": "Contacts",
  "address": "Adresse",
  "accountNumber": "Numéro de compte",
  "bookingCompleted": "Reservation complétée",
  "residenceInformation": "Informations de la résidence",
  "active": "Active",
  "reserved": "Réserver",

  // Add Residence
  "addResidence": "Ajouter une résidence",
  "uploadPhoto": 'téléchargez 5 photos',
  "residencName": "Nom de la résidence",
  "ownerInformation": "Information du propriétaire",
  "capacityPerson": " Capacité/personne",
  "beds": "Chambres",
  "bath": "Douches",
  "city": "ville",
  "rentHr": "Louer/heure",
  "aboutResidence": "À propos de l résidence",
  "municipality": "Commune",
  "quartar": "Quartier",
  "setAmount": "Ajoutez le prix de votre résidence",
  "setCategory": "Définir la catégorie de résidence",
  "setAminities": "Définir les commodités de la résidence",
  "about": "À propos",
  "add": "Ajouter",

  // animities
  "wifi": "wifi",
  "air-conditioner": "climatiseur",
  "pets": "animaux domestiques",
  "kitchen": "cuisine",
  "tv": "la télé",
  "internet": "l'Internet",
  "washing-machine": "machine à laver",
  "dryer": "séchoir",
  "refrigerator": "réfrigérateur",
  "heating": "chauffage",
  "parking": "parking",

  "Enter how many beds": "Nombre de chambre",
  "Enter how many baths": "Nombres de douches",
  "Enter residence address": "Entrez l'adresse de la residence",
  "Enter city name": "Entrez le nom de la ville",
  "Enter municipality name": "Entrez la commune",
  "Enter quartier": "Entrez le quartier",

  "Enter Residence Name": "Entrez le nom de la résidence",
  "Enter person number": "Entrer le nombre de personne ",

  "Enter about residence": "Entrez à propos de la résidence",
  "Enter name": "Entrez le nom",
  "About yourself": "A propos de toi",

  "ownerName": "Nom du Gérant",

  //setting
  "Languages": "Langues",
  "settings": "Paramètres",
  "changePassword": "Changez le mot de passe",
  "termsServices": "Conditions de services",
  "Privacy Policy": "politique de confidentialité",
  "FAQ": "FAQ",
  "Language Change": "Changement de langue",

  "New Password" : "nouveau mot de passe",
  "Current Password" : "Mot de passe actuel",
  "Confirm New Password" : "Confirmer le nouveau mot de passe",
  "continue" : "Continuez",
  "selectMethod" : "Sélectionnez la méthode",
  "withdrawMethod" : "Méthode de retrait",

  "Enter password" : "Entrer le mot de passe",
  "Enter new Password" : "Entrez un nouveau mot de passe",
  "Enter confirm Password" : "Entrez confirmer le mot de passe",
  "Enter your account number" : "Entrez votre numéro de compte",

  //income
  "Daily Income": "Revenu quotidien",
  "Weekly Income": "Revenu hebdomadaire",
  "Monthly Income": "Revenu mensuel",
  "Total Income": "Revenu total",
  'logOutAlert': "Vous voulez vraiment vous déconnecter ?",

  //notificationout
  "Notification": "Notification",

  // toast message
  "Log out Successfully": "Déconnexion réussie",
  "Please enter your name": "S'il vous plaît entrez votre nom",
  "YYYY": "AAAA",
  "MM": "MM",
  "DD": "JJ",

  "Please enter your password": "s'il vous plait entrez votre mot de passe",
  "Please use uppercase,lowercase,spacial character and number":
      "Veuillez utiliser des majuscules, des minuscules, des espaces et des chiffres.",
  "Please use 8 character long password":
      "Veuillez utiliser un mot de passe de 8 caractères",
  "Password doesn't match": "Le mot de passe ne correspond pas",
  "Please enter your address": "Veuillez entrer votre adresse",
  "Please enter your account number": "Veuillez entrer votre numéro de compte",
  "Sign up successfully": "Inscrivez-vous avec succès",
  "Something went wrong": "Quelque chose s'est mal passé",
  "Success": "Succès",
  "OTP sent to your email": "OTP envoyé à votre adresse e-mail",

  //booking details
  "Payment": "Paiement",
  "Total Amount": 'Montant total',
  "Total Time": "Temps total",
  "Date": "Date",
  "Total Person": "Personne totale",
  "User Contact": "Contact utilisateur",
  "User Name": "Nom d'utilisateur",
  'Booking Information': 'Informations de réservation',

  'User Contact Information': "Coordonnées de l'utilisateur",
  'Contact': 'Contact',
  'Email': 'E-mail',
  'Address': 'Adresse',

  "Booking Request Details": "Détails de la demande de réservation",
  "Cancel": "Annulez",
  "Approve": "Approuvez",

  'Check In': 'Enregistrement',
  'Check Out': 'Vérifier',
  'Payment Types': 'Types de paiement',

  "You can only select up to 5 images":
      "Vous ne pouvez sélectionner que jusqu'à 5 images",
  "Pick 5 images": "Choisissez 5 images ",
  "Pick only 5 images": "Choisissez seulement 5 images",
  "No image selected": "Aucune image sélectionnée",
  "Successfully residence added": "Résidence ajoutée avec succès",
  "Successfully residence updated": "Résidence mise à jour avec succès",
  "Image File too large": "Fichier image trop volumineux",

  "Successfully profile updated": "Profil mis à jour avec succès",
  "See Details": "Voir les détails",
  "Please enter your valid email": "Veuillez entrer votre email valide",
  "Sign in successfully": "Connectez-vous avec succès",
  "Enter your address": "Entrez votre adresse",
  "Please enter your email": "Veuillez entrer votre email",

  'Total Days': 'Nombre total de jours',
  'Total Hours': 'Heures totales',
  "enter  hours amount": "saisir le montant horaire",
  "Enter daily amount": "Entrez le montant quotidien",
  "hr": "hr",
  "day": "day",
  "\$00 / hr": "FCFA 00/heure",
  "\$00 / day": "FCFA 00 / jour",
  "Available Balance": "Solde disponible",
  "Wallet": "Portefeuille",
  'Withdraw Money': "Retirer de l'argent",
  'Card number': 'Numéro de carte',
  "Enter your Credit card number": "Entrez votre numéro de carte de crédit",
  'Amount': 'Montant',
  "Enter withdraw amount": "Entrez le montant du retrait",
  "Enter your Credit card number": "Entrez votre numéro de carte de crédit",
  "Withdrawn Mode": "mode de retrait",
  "Select withdrawals": "Sélectionnez les retraits",
  'Withdraw': 'Retrait',
  "Please wait for admin approval" : "Veuillez attendre l'approbation de l'administrateur",
  "Enter your amount" : "Entrez votre montant",
  'Past Weekly Income' : 'Revenu hebdomadaire passé',
  'Recent Week' :  'Semaine récente',
  'Week no. ' : "Semaine non. ",
  'Service charge': 'Frais de service',
  'Residence charge' : 'Frais de séjour',
  "Select your payment method" : "Sélectionnez votre méthode de paiement",
  "User Already Exist" : "L'utilisateur existe déjà",
  "Hotel": "Chambre",
  "Residence" : "Résidence",
  "PersonalHouse" : "Maison-personnelle",
  'Enter Your Phone Number': 'Entrez votre numéro de téléphone',
  "Enter Your Valid Phone Number" : "Entrez votre numéro de téléphone valide",
  'Phone Number' : 'Numéro de téléphone',
  "Image file too Large" : "Fichier image trop volumineux",

  "Set New Password": "Configurez votre mot de passe",
  "Your password must have 8-10 characters.":
  "Le mot de passe doit contenir 8-10 characters.",
  'New Password': 'Nouveau mot de passe',
  "Enter new password": "Entrez le nouveau mot de passe",
  "Please use strong password": "Veuillez utiliser un mot de passe fort",
  "Please use 8 character long password": "Veuillez utiliser un mot de passe de 8 caractères",
  'Confirm Password': 'Confirmer le mot de passe',
  'Confirm password': 'Confirmer le mot de passe',
  "Password doesn't match": "Le mot de passe ne correspond pas",
  "Reset": "Renitialisez",
  "Please fill up your email field":"Veuillez remplir votre champ email",

  "FCFA /hr" : "FCFA /heure",
  "FCFA /day" : "FCFA /jour",
  "FCFA /Half-day" : "FCFA /jour",
  "\$00 / Half-day": "FCFA 00 / Demi-jour",

  "Select Country" : "Pays",
  "Otp send to your email" : "OTP envoyer à votre email",
  "Delete Account" : "Supprimer le compte",
  "Must provide appropiate data" : "Doit fournir des données appropriées",
  "Enter your current password to delete your account" : "Entrez votre mot de passe actuel pour supprimer votre compte",


};
